"""add pdf fields to jobs

Revision ID: 06607c99f84c
Revises: e800df236ddb
Create Date: 2026-03-01 00:32:52.137101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06607c99f84c'
down_revision: Union[str, Sequence[str], None] = 'e800df236ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_pdf_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('compressed_pdf_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pdf_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pdf_commands_json', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_pdf_status'), ['pdf_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_pdf_status'))
        batch_op.drop_column('pdf_commands_json')
        batch_op.drop_column('pdf_status')
        batch_op.drop_column('compressed_pdf_path')
        batch_op.drop_column('source_pdf_path')

    # ### end Alembic commands ###
